// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, description, published_at, url, created_at, updated_at, feed_id) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, title, description, published_at, url, created_at, updated_at, feed_id
`

type CreatePostParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	PublishedAt pgtype.Timestamp
	Url         string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	FeedID      pgtype.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
	)
	return i, err
}
